In [3]:
class Employee:
    employee_count = 0

    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1

    @classmethod
    def average_salary(my_cls, employees):
        if not employees:
            return 0
        total_salary = sum(employee.salary for employee in employees)
        return total_salary / len(employees)

    def display_info(self):
        print(f"Name: {self.name}")
        print(f"Family: {self.family}")
        print(f"Salary: ${self.salary}")
        print(f"Department: {self.department}")


class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department, benefits):
        super().__init__(name, family, salary, department)

    def display_info(self):
        super().display_info()

def main():
    employee1 = Employee("Dhanalakshmi", "Nangunuri", 500000, "IT")
    employee2 = Employee("Basha", "Shaik", 650000, "Managment")
    fulltime_employee1 = FulltimeEmployee("Keerthi", "Peddinti", 800000, "IT", "Health Insurance")
    fulltime_employee2 = FulltimeEmployee("Anirudh", "Pudicheti", 750000, "IT", "Health Insurance")

    print("Employee 1:")
    employee1.display_info()
    print("\nEmployee 2:")
    employee2.display_info()
    print("\nFulltime Employee 1:")
    fulltime_employee1.display_info()
    print("\nFulltime Employee 2:")
    fulltime_employee2.display_info()
    employees = [employee1, employee2, fulltime_employee1, fulltime_employee2]
    avg_salary = Employee.average_salary(employees)
    print(f"\nAverage Salary: ${avg_salary:.2f}")
    print(f"\nTotal number of employees: {Employee.employee_count}")

if __name__ == "__main__":
    main()

Employee 1:
Name: Dhanalakshmi
Family: Nangunuri
Salary: $500000
Department: IT

Employee 2:
Name: Basha
Family: Shaik
Salary: $650000
Department: Managment

Fulltime Employee 1:
Name: Keerthi
Family: Peddinti
Salary: $800000
Department: IT

Fulltime Employee 2:
Name: Anirudh
Family: Pudicheti
Salary: $750000
Department: IT

Average Salary: $675000.00

Total number of employees: 4


The program starts in the main() function, where instances of the Employee and FulltimeEmployee classes are created. Each instance is initialized with unique details such as name, family, salary, and department.

The constructor initializes instance variables (name, family, salary, department) for each employee. It also updates the class variable employee_count to track the total number of employees and increments the total_salary to track their combined salaries.

The FulltimeEmployee class inherits all properties and methods from the Employee class. The super() function is used to initialize the Employee class attributes, and an additional benefits attribute is added for full-time employees.

The average_salary class method calculates the average salary by summing up the salaries of all employees and dividing by the total number of employees. It uses the employee_count and total_salary class variables.

The program prints the total number of employees using the employee_count class variable. It also prints the average salary using the average_salary method.

The display_info method prints the details of each employee, including name, family, salary, and department. The FulltimeEmployee class overrides this method to include benefits.

In [2]:
import numpy as np

array = np.random.uniform(1, 20, 20)

reshaped_array = array.reshape(4, 5)

max_replacenums = reshaped_array == np.max(reshaped_array, axis=1, keepdims=True)

result = np.where(max_replacenums, 0, reshaped_array)

print("Original vector:")
print(array)
print("\nReshaped array (4x5):")
print(reshaped_array)
print("\nArray with max values replaced by 0 in each row:")
print(result)

Original vector:
[17.31438454  1.03810163  8.68387619 14.70236543 19.91157826  2.48851325
 15.92148391 12.2127863  16.0692941  12.40129937  9.80806374  2.4517171
 19.5983044   5.48669794  6.98993497 16.44792652  3.26651621 14.45508207
  5.35974236  5.57519162]

Reshaped array (4x5):
[[17.31438454  1.03810163  8.68387619 14.70236543 19.91157826]
 [ 2.48851325 15.92148391 12.2127863  16.0692941  12.40129937]
 [ 9.80806374  2.4517171  19.5983044   5.48669794  6.98993497]
 [16.44792652  3.26651621 14.45508207  5.35974236  5.57519162]]

Array with max values replaced by 0 in each row:
[[17.31438454  1.03810163  8.68387619 14.70236543  0.        ]
 [ 2.48851325 15.92148391 12.2127863   0.         12.40129937]
 [ 9.80806374  2.4517171   0.          5.48669794  6.98993497]
 [ 0.          3.26651621 14.45508207  5.35974236  5.57519162]]


The program starts by importing numpy and creating a random array of 20 numbers between 1 and 20. The array is reshaped into a 4x5 format for easier row and column operations. The largest number in each row is found using np.max with axis=1. The largest number in each row is replaced with 0 using np.where. The program prints both the original array and the modified array where the maximum values are replaced by 0.